---
title: "Exploratory Data Analysis"
author: "ak5357"
date: "2024-10-03"
output: html_document
---

```{r setup, include=FALSE}
library(tidyverse)
library(dplyr)
```


## Import weather data.
```{r import_weather_data}
weather_df = 
  rnoaa::meteo_pull_monitors(
    c("USW00094728", "USW00022534", "USS0023B17S"),
    var = c("PRCP", "TMIN", "TMAX"), 
    date_min = "2021-01-01",
    date_max = "2022-12-31") |>
  mutate(
    name = case_match(
      id, 
      "USW00094728" ~ "CentralPark_NY", 
      "USW00022534" ~ "Molokai_HI",
      "USS0023B17S" ~ "Waterhole_WA"),
    tmin = tmin / 10,
    tmax = tmax / 10,
    month = lubridate::floor_date(date, unit = "month")) |>
  select(name, id, everything())
```

## Exploratory visuals
```{r weather_hist}
weather_df |> 
  ggplot(aes(x = prcp)) + 
  geom_histogram()
```


```{r weather_low_prcp}
weather_df |> 
  filter(prcp >= 1000)
```

```{r weather_plot_1}
weather_df |> 
  filter(tmax >= 20, tmax <= 30) |> 
  ggplot(aes(x = tmin, y = tmax, color = name, shape = name)) + 
  geom_point(alpha = .75)
```


## `group_by()`
```{r weather_group_by}
# Group by name and get n obs per name
weather_df |> 
  group_by(name) |> 
  summarize(n_obs = n())

# Group by month and get n obs per name
weather_df |> 
  group_by(month) |> 
  summarize(n_obs = n())

# Group by name and get n obs per name & n distinct months with measures
weather_df |> 
  group_by(name) |> 
  summarize(
    n_obs = n(),
    n_dist = n_distinct(month))

# Group by both name and month and get count for each
weather_df |> 
  group_by(name, month) |> 
  summarize(n_obs = n())
```


**Count without grouping.**
```{r weather_counting}
weather_df |>
  count(month, name = "n_obs")
```

## 2x 2
```{r weather_2x2}
weather_df |> 
  drop_na(tmax) |> 
  mutate(
    cold = case_when(
      tmax < 5 ~ "cold",
      tmax >= 5 ~ "not cold"
    )
  ) |> 
  group_by(name, cold) |> 
  summarize(count = n())
```


```{r janitor_tabyl}
weather_df |> 
  drop_na(tmax) |> 
  mutate(
    cold = case_when(
      tmax < 5 ~ "cold",
      tmax >= 5 ~ "not_cold"
    )
  ) |> 
  janitor::tabyl(name, cold)
```










